/**
 * Client-safe static book list
 * Hardcoded from index.json — no filesystem access needed
 */

export interface BookFilterItem {
  name: string
  abbr: string
  testament: 'OT' | 'NT'
}

export const BIBLE_BOOKS: BookFilterItem[] = [
  { name: 'Genesis', abbr: 'Gen', testament: 'OT' },
  { name: 'Exodus', abbr: 'Exod', testament: 'OT' },
  { name: 'Leviticus', abbr: 'Lev', testament: 'OT' },
  { name: 'Numbers', abbr: 'Num', testament: 'OT' },
  { name: 'Deuteronomy', abbr: 'Deut', testament: 'OT' },
  { name: 'Joshua', abbr: 'Josh', testament: 'OT' },
  { name: 'Judges', abbr: 'Judg', testament: 'OT' },
  { name: 'Ruth', abbr: 'Ruth', testament: 'OT' },
  { name: '1 Samuel', abbr: '1Sam', testament: 'OT' },
  { name: '2 Samuel', abbr: '2Sam', testament: 'OT' },
  { name: '1 Kings', abbr: '1Kgs', testament: 'OT' },
  { name: '2 Kings', abbr: '2Kgs', testament: 'OT' },
  { name: '1 Chronicles', abbr: '1Chr', testament: 'OT' },
  { name: '2 Chronicles', abbr: '2Chr', testament: 'OT' },
  { name: 'Ezra', abbr: 'Ezra', testament: 'OT' },
  { name: 'Nehemiah', abbr: 'Neh', testament: 'OT' },
  { name: 'Esther', abbr: 'Esth', testament: 'OT' },
  { name: 'Job', abbr: 'Job', testament: 'OT' },
  { name: 'Psalms', abbr: 'Ps', testament: 'OT' },
  { name: 'Proverbs', abbr: 'Prov', testament: 'OT' },
  { name: 'Ecclesiastes', abbr: 'Eccl', testament: 'OT' },
  { name: 'Song of Solomon', abbr: 'Song', testament: 'OT' },
  { name: 'Isaiah', abbr: 'Isa', testament: 'OT' },
  { name: 'Jeremiah', abbr: 'Jer', testament: 'OT' },
  { name: 'Lamentations', abbr: 'Lam', testament: 'OT' },
  { name: 'Ezekiel', abbr: 'Ezek', testament: 'OT' },
  { name: 'Daniel', abbr: 'Dan', testament: 'OT' },
  { name: 'Hosea', abbr: 'Hos', testament: 'OT' },
  { name: 'Joel', abbr: 'Joel', testament: 'OT' },
  { name: 'Amos', abbr: 'Amos', testament: 'OT' },
  { name: 'Obadiah', abbr: 'Obad', testament: 'OT' },
  { name: 'Jonah', abbr: 'Jonah', testament: 'OT' },
  { name: 'Micah', abbr: 'Mic', testament: 'OT' },
  { name: 'Nahum', abbr: 'Nah', testament: 'OT' },
  { name: 'Habakkuk', abbr: 'Hab', testament: 'OT' },
  { name: 'Zephaniah', abbr: 'Zeph', testament: 'OT' },
  { name: 'Haggai', abbr: 'Hag', testament: 'OT' },
  { name: 'Zechariah', abbr: 'Zech', testament: 'OT' },
  { name: 'Malachi', abbr: 'Mal', testament: 'OT' },
  { name: 'Matthew', abbr: 'Matt', testament: 'NT' },
  { name: 'Mark', abbr: 'Mark', testament: 'NT' },
  { name: 'Luke', abbr: 'Luke', testament: 'NT' },
  { name: 'John', abbr: 'John', testament: 'NT' },
  { name: 'Acts', abbr: 'Acts', testament: 'NT' },
  { name: 'Romans', abbr: 'Rom', testament: 'NT' },
  { name: '1 Corinthians', abbr: '1Cor', testament: 'NT' },
  { name: '2 Corinthians', abbr: '2Cor', testament: 'NT' },
  { name: 'Galatians', abbr: 'Gal', testament: 'NT' },
  { name: 'Ephesians', abbr: 'Eph', testament: 'NT' },
  { name: 'Philippians', abbr: 'Phil', testament: 'NT' },
  { name: 'Colossians', abbr: 'Col', testament: 'NT' },
  { name: '1 Thessalonians', abbr: '1Thess', testament: 'NT' },
  { name: '2 Thessalonians', abbr: '2Thess', testament: 'NT' },
  { name: '1 Timothy', abbr: '1Tim', testament: 'NT' },
  { name: '2 Timothy', abbr: '2Tim', testament: 'NT' },
  { name: 'Titus', abbr: 'Titus', testament: 'NT' },
  { name: 'Philemon', abbr: 'Phlm', testament: 'NT' },
  { name: 'Hebrews', abbr: 'Heb', testament: 'NT' },
  { name: 'James', abbr: 'Jas', testament: 'NT' },
  { name: '1 Peter', abbr: '1Pet', testament: 'NT' },
  { name: '2 Peter', abbr: '2Pet', testament: 'NT' },
  { name: '1 John', abbr: '1John', testament: 'NT' },
  { name: '2 John', abbr: '2John', testament: 'NT' },
  { name: '3 John', abbr: '3John', testament: 'NT' },
  { name: 'Jude', abbr: 'Jude', testament: 'NT' },
  { name: 'Revelation', abbr: 'Rev', testament: 'NT' },
]
