/**
 * Verse of the Day system
 * 365 curated verses — one for each day, deterministic by date (no server needed)
 */

export interface DailyVerse {
  book: string
  slug: string
  chapter: number
  verse: number
  text: string
  reference: string
}

// 365 impactful verses from across the BSB, curated to cover major themes
// Format: [book, slug, chapter, verse, text]
const DAILY_VERSES: [string, string, number, number, string][] = [
  // January (31)
  ['Genesis', 'genesis', 1, 1, 'In the beginning God created the heavens and the earth.'],
  ['Psalms', 'psalms', 23, 1, 'The LORD is my shepherd; I shall not want.'],
  ['Proverbs', 'proverbs', 3, 5, 'Trust in the LORD with all your heart, and lean not on your own understanding.'],
  ['Isaiah', 'isaiah', 40, 31, 'But those who wait upon the LORD will renew their strength; they will mount up with wings like eagles; they will run and not grow weary; they will walk and not faint.'],
  ['Jeremiah', 'jeremiah', 29, 11, 'For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, to give you a future and a hope.'],
  ['John', 'john', 3, 16, 'For God so loved the world that He gave His one and only Son, that everyone who believes in Him shall not perish but have eternal life.'],
  ['Romans', 'romans', 8, 28, 'And we know that God works all things together for the good of those who love Him, who are called according to His purpose.'],
  ['Philippians', 'philippians', 4, 13, 'I can do all things through Christ who gives me strength.'],
  ['Psalms', 'psalms', 46, 10, 'Be still and know that I am God; I will be exalted among the nations, I will be exalted over the earth.'],
  ['Matthew', 'matthew', 11, 28, 'Come to Me, all you who are weary and burdened, and I will give you rest.'],
  ['Psalms', 'psalms', 119, 105, 'Your word is a lamp to my feet and a light to my path.'],
  ['Romans', 'romans', 12, 2, 'Do not be conformed to this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what is the good, pleasing, and perfect will of God.'],
  ['2 Timothy', '2-timothy', 3, 16, 'All Scripture is God-breathed and is useful for instruction, for conviction, for correction, and for training in righteousness,'],
  ['Hebrews', 'hebrews', 11, 1, 'Now faith is the assurance of what we hope for and the certainty of what we do not see.'],
  ['Joshua', 'joshua', 1, 9, 'Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God is with you wherever you go.'],
  ['Psalms', 'psalms', 27, 1, 'The LORD is my light and my salvation— whom shall I fear? The LORD is the stronghold of my life— of whom shall I be afraid?'],
  ['Galatians', 'galatians', 5, 22, 'But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness,'],
  ['1 Corinthians', '1-corinthians', 13, 4, 'Love is patient, love is kind. It does not envy, it does not boast, it is not proud.'],
  ['Ephesians', 'ephesians', 2, 8, 'For it is by grace you have been saved through faith, and this not from yourselves; it is the gift of God,'],
  ['Psalms', 'psalms', 37, 4, 'Delight yourself in the LORD, and He will give you the desires of your heart.'],
  ['Isaiah', 'isaiah', 41, 10, 'Do not fear, for I am with you; do not be afraid, for I am your God. I will strengthen you; I will surely help you; I will uphold you with My righteous right hand.'],
  ['Proverbs', 'proverbs', 16, 3, 'Commit your works to the LORD and your plans will be established.'],
  ['John', 'john', 14, 6, 'Jesus answered, "I am the way and the truth and the life. No one comes to the Father except through Me."'],
  ['Psalms', 'psalms', 91, 1, 'He who dwells in the shelter of the Most High will rest in the shadow of the Almighty.'],
  ['Romans', 'romans', 5, 8, 'But God proves His love for us in this: While we were still sinners, Christ died for us.'],
  ['Philippians', 'philippians', 4, 6, 'Be anxious for nothing, but in everything, by prayer and petition, with thanksgiving, present your requests to God.'],
  ['Matthew', 'matthew', 6, 33, 'But seek first the kingdom of God and His righteousness, and all these things will be added unto you.'],
  ['Psalms', 'psalms', 34, 8, 'Taste and see that the LORD is good; blessed is the man who takes refuge in Him.'],
  ['1 Peter', '1-peter', 5, 7, 'Cast all your anxiety on Him, because He cares for you.'],
  ['Lamentations', 'lamentations', 3, 22, 'Because of the loving devotion of the LORD we are not consumed, for His compassions never fail.'],
  ['Colossians', 'colossians', 3, 23, 'Whatever you do, work at it with your whole being, for the Lord and not for men,'],

  // February (28)
  ['Psalms', 'psalms', 139, 14, 'I praise You, for I am fearfully and wonderfully made. Marvelous are Your works, and I know this very well.'],
  ['Proverbs', 'proverbs', 4, 23, 'Guard your heart with all diligence, for from it flow springs of life.'],
  ['John', 'john', 1, 1, 'In the beginning was the Word, and the Word was with God, and the Word was God.'],
  ['Romans', 'romans', 10, 9, 'that if you confess with your mouth, "Jesus is Lord," and believe in your heart that God raised Him from the dead, you will be saved.'],
  ['Psalms', 'psalms', 100, 4, 'Enter His gates with thanksgiving and His courts with praise; give thanks to Him and bless His name.'],
  ['Isaiah', 'isaiah', 53, 5, 'But He was pierced for our transgressions, He was crushed for our iniquities; the punishment that brought us peace was upon Him, and by His stripes we are healed.'],
  ['Matthew', 'matthew', 5, 16, 'In the same way, let your light shine before men, that they may see your good deeds and glorify your Father in heaven.'],
  ['Psalms', 'psalms', 121, 1, 'I lift my eyes to the mountains. Where does my help come from?'],
  ['James', 'james', 1, 5, 'Now if any of you lacks wisdom, he should ask God, who gives generously to all without finding fault, and it will be given to him.'],
  ['John', 'john', 8, 32, 'Then you will know the truth, and the truth will set you free.'],
  ['Ephesians', 'ephesians', 6, 10, 'Finally, be strong in the Lord and in His mighty power.'],
  ['Psalms', 'psalms', 51, 10, 'Create in me a clean heart, O God, and renew a right spirit within me.'],
  ['Proverbs', 'proverbs', 22, 6, 'Train up a child in the way he should go, and when he is old he will not depart from it.'],
  ['1 John', '1-john', 4, 19, 'We love because He first loved us.'],
  ['Psalms', 'psalms', 56, 3, 'When I am afraid, I will trust in You.'],
  ['Romans', 'romans', 6, 23, 'For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.'],
  ['2 Corinthians', '2-corinthians', 5, 17, 'Therefore if anyone is in Christ, he is a new creation. The old has passed away. Behold, the new has come!'],
  ['Psalms', 'psalms', 19, 1, 'The heavens declare the glory of God; the skies proclaim the work of His hands.'],
  ['Matthew', 'matthew', 28, 19, 'Therefore go and make disciples of all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Spirit,'],
  ['Psalms', 'psalms', 73, 26, 'My flesh and my heart may fail, but God is the strength of my heart and my portion forever.'],
  ['Proverbs', 'proverbs', 18, 10, 'The name of the LORD is a strong tower; the righteous run to it and are safe.'],
  ['John', 'john', 10, 10, 'The thief comes only to steal and kill and destroy. I have come that they may have life, and have it in all its fullness.'],
  ['Psalms', 'psalms', 103, 12, 'As far as the east is from the west, so far has He removed our transgressions from us.'],
  ['1 Thessalonians', '1-thessalonians', 5, 16, 'Rejoice at all times.'],
  ['Micah', 'micah', 6, 8, 'He has shown you, O man, what is good. And what does the LORD require of you but to act justly, to love mercy, and to walk humbly with your God?'],
  ['Psalms', 'psalms', 145, 18, 'The LORD is near to all who call on Him, to all who call on Him in truth.'],
  ['Hebrews', 'hebrews', 13, 8, 'Jesus Christ is the same yesterday and today and forever.'],
  ['Psalms', 'psalms', 150, 6, 'Let everything that has breath praise the LORD! Hallelujah!'],

  // March (31)
  ['Deuteronomy', 'deuteronomy', 31, 6, 'Be strong and courageous; do not be afraid or terrified of them, for the LORD your God goes with you; He will never leave you nor forsake you.'],
  ['Psalms', 'psalms', 62, 1, 'My soul finds rest in God alone; my salvation comes from Him.'],
  ['Proverbs', 'proverbs', 14, 12, 'There is a way that seems right to a man, but its end is the way of death.'],
  ['John', 'john', 15, 5, 'I am the vine; you are the branches. The one who remains in Me, and I in him, will bear much fruit. For apart from Me you can do nothing.'],
  ['Romans', 'romans', 1, 16, 'I am not ashamed of the gospel, for it is the power of God for salvation to everyone who believes, first to the Jew, then to the Greek.'],
  ['Psalms', 'psalms', 42, 1, 'As the deer pants for streams of water, so my soul longs for You, O God.'],
  ['Isaiah', 'isaiah', 55, 8, '"For My thoughts are not your thoughts, neither are your ways My ways," declares the LORD.'],
  ['Matthew', 'matthew', 7, 7, 'Ask, and it will be given to you; seek, and you will find; knock, and the door will be opened to you.'],
  ['Psalms', 'psalms', 118, 24, 'This is the day that the LORD has made; let us rejoice and be glad in it.'],
  ['Colossians', 'colossians', 3, 2, 'Set your minds on things above, not on earthly things.'],
  ['Proverbs', 'proverbs', 27, 17, 'As iron sharpens iron, so one man sharpens another.'],
  ['2 Timothy', '2-timothy', 1, 7, 'For God has not given us a spirit of fear, but of power, love, and self-control.'],
  ['Psalms', 'psalms', 16, 11, 'You have made known to me the path of life; You fill me with joy in Your presence, with eternal pleasures at Your right hand.'],
  ['1 Corinthians', '1-corinthians', 10, 13, 'No temptation has seized you except what is common to man. And God is faithful; He will not let you be tempted beyond what you can bear.'],
  ['John', 'john', 16, 33, 'I have told you these things so that in Me you may have peace. In the world you will have tribulation. But take courage; I have overcome the world!'],
  ['Psalms', 'psalms', 40, 1, 'I waited patiently for the LORD, and He turned to me and heard my cry.'],
  ['Ephesians', 'ephesians', 3, 20, 'Now to Him who is able to do immeasurably more than all we ask or imagine, according to His power that is at work within us,'],
  ['Proverbs', 'proverbs', 1, 7, 'The fear of the LORD is the beginning of knowledge, but fools despise wisdom and discipline.'],
  ['Matthew', 'matthew', 22, 37, 'Jesus declared, "Love the Lord your God with all your heart and with all your soul and with all your mind."'],
  ['Psalms', 'psalms', 55, 22, 'Cast your burden upon the LORD and He will sustain you; He will never let the righteous be shaken.'],
  ['Romans', 'romans', 15, 13, 'May the God of hope fill you with all joy and peace as you believe in Him, so that you may overflow with hope by the power of the Holy Spirit.'],
  ['James', 'james', 4, 8, 'Draw near to God, and He will draw near to you.'],
  ['Psalms', 'psalms', 63, 1, 'O God, You are my God; earnestly I seek You. My soul thirsts for You; my body yearns for You in a dry and weary land without water.'],
  ['1 John', '1-john', 1, 9, 'If we confess our sins, He is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.'],
  ['Proverbs', 'proverbs', 31, 30, 'Charm is deceptive and beauty is fleeting, but a woman who fears the LORD is to be praised.'],
  ['John', 'john', 11, 25, 'Jesus said to her, "I am the resurrection and the life. The one who believes in Me will live, even though he dies."'],
  ['Psalms', 'psalms', 84, 11, 'For the LORD God is a sun and shield; the LORD gives grace and glory. He withholds no good thing from those who walk with integrity.'],
  ['Hebrews', 'hebrews', 4, 12, 'For the word of God is living and active. Sharper than any double-edged sword, it pierces even to dividing soul and spirit, joints and marrow. It judges the thoughts and intentions of the heart.'],
  ['Matthew', 'matthew', 5, 44, 'But I tell you, love your enemies and pray for those who persecute you,'],
  ['Psalms', 'psalms', 90, 12, 'Teach us to number our days, that we may present a heart of wisdom.'],
  ['Revelation', 'revelation', 21, 4, 'He will wipe away every tear from their eyes, and there will be no more death or mourning or crying or pain, for the former things have passed away.'],

  // April (30)
  ['Psalms', 'psalms', 1, 1, 'Blessed is the man who does not walk in the counsel of the wicked, or set foot on the path of sinners, or sit in the seat of mockers.'],
  ['Proverbs', 'proverbs', 11, 14, 'Where there is no guidance, a people will fall, but with many counselors there is deliverance.'],
  ['John', 'john', 6, 35, 'Jesus answered, "I am the bread of life. Whoever comes to Me will never hunger, and whoever believes in Me will never thirst."'],
  ['Romans', 'romans', 3, 23, 'for all have sinned and fall short of the glory of God,'],
  ['Psalms', 'psalms', 4, 8, 'I will lie down and sleep in peace, for You alone, O LORD, make me dwell in safety.'],
  ['Isaiah', 'isaiah', 26, 3, 'You will keep in perfect peace those whose minds are steadfast, because they trust in You.'],
  ['Matthew', 'matthew', 19, 26, 'Jesus looked at them and said, "With man this is impossible, but with God all things are possible."'],
  ['Psalms', 'psalms', 107, 1, 'Give thanks to the LORD, for He is good; His loving devotion endures forever.'],
  ['1 Corinthians', '1-corinthians', 16, 13, 'Be on the alert. Stand firm in the faith. Be men of courage. Be strong.'],
  ['Proverbs', 'proverbs', 19, 21, 'Many are the plans in a man\'s heart, but the purpose of the LORD will prevail.'],
  ['Psalms', 'psalms', 138, 8, 'The LORD will fulfill His purpose for me. O LORD, Your loving devotion endures forever— do not abandon the works of Your hands.'],
  ['John', 'john', 14, 27, 'Peace I leave with you; My peace I give to you. I do not give to you as the world gives. Do not let your hearts be troubled; do not be afraid.'],
  ['Ephesians', 'ephesians', 4, 32, 'Be kind and tenderhearted to one another, forgiving each other just as in Christ God forgave you.'],
  ['Psalms', 'psalms', 32, 8, 'I will instruct you and teach you the way you should go; I will counsel you with My eye upon you.'],
  ['Proverbs', 'proverbs', 12, 1, 'Whoever loves discipline loves knowledge, but he who hates correction is stupid.'],
  ['Matthew', 'matthew', 6, 34, 'Therefore do not worry about tomorrow, for tomorrow will worry about itself. Today has enough trouble of its own.'],
  ['Psalms', 'psalms', 147, 3, 'He heals the brokenhearted and binds up their wounds.'],
  ['Romans', 'romans', 8, 1, 'Therefore there is now no condemnation for those who are in Christ Jesus.'],
  ['Galatians', 'galatians', 6, 9, 'Let us not grow weary in doing good, for in due time we will reap a harvest if we do not give up.'],
  ['Psalms', 'psalms', 18, 2, 'The LORD is my rock, my fortress, and my deliverer. My God is my rock, in whom I take refuge. He is my shield, the horn of my salvation, my stronghold.'],
  ['1 Timothy', '1-timothy', 2, 5, 'For there is one God and one mediator between God and mankind, the man Christ Jesus,'],
  ['Proverbs', 'proverbs', 3, 6, 'in all your ways acknowledge Him, and He will make your paths straight.'],
  ['John', 'john', 4, 24, 'God is Spirit, and His worshipers must worship Him in spirit and in truth.'],
  ['Psalms', 'psalms', 46, 1, 'God is our refuge and strength, an ever-present help in times of trouble.'],
  ['Acts', 'acts', 17, 11, 'Now the Bereans were more noble-minded than the Thessalonians, for they received the message with great eagerness and examined the Scriptures every day to see if these teachings were true.'],
  ['Psalms', 'psalms', 143, 8, 'Let me hear Your loving devotion in the morning, for I have put my trust in You. Teach me the way I should walk, for I lift up my soul to You.'],
  ['Proverbs', 'proverbs', 10, 9, 'He who walks in integrity walks securely, but he who perverts his ways will be found out.'],
  ['Matthew', 'matthew', 7, 24, 'Therefore everyone who hears these words of Mine and acts on them is like a wise man who built his house on the rock.'],
  ['Psalms', 'psalms', 5, 3, 'In the morning, O LORD, You hear my voice; at daybreak I lay my plea before You and wait in expectation.'],
  ['1 John', '1-john', 3, 1, 'Behold what manner of love the Father has given to us, that we should be called children of God. And that is what we are!'],

  // May (31)
  ['Psalms', 'psalms', 23, 4, 'Even though I walk through the valley of the shadow of death, I will fear no evil, for You are with me; Your rod and Your staff, they comfort me.'],
  ['Proverbs', 'proverbs', 15, 1, 'A gentle answer turns away wrath, but a harsh word stirs up anger.'],
  ['John', 'john', 13, 34, 'A new commandment I give you: Love one another. As I have loved you, so you also must love one another.'],
  ['Romans', 'romans', 8, 38, 'For I am convinced that neither death nor life, neither angels nor principalities, neither the present nor the future, nor any powers,'],
  ['Psalms', 'psalms', 66, 1, 'Shout for joy to God, all the earth!'],
  ['Isaiah', 'isaiah', 43, 2, 'When you pass through the waters, I will be with you; and when you walk through the fire, you will not be scorched; the flames will not set you ablaze.'],
  ['Matthew', 'matthew', 11, 29, 'Take My yoke upon you and learn from Me; for I am gentle and humble in heart, and you will find rest for your souls.'],
  ['Psalms', 'psalms', 86, 5, 'For You, O Lord, are good and forgiving, rich in loving devotion to all who call on You.'],
  ['Philippians', 'philippians', 2, 3, 'Do nothing out of selfish ambition or empty pride, but in humility consider others more important than yourselves.'],
  ['Proverbs', 'proverbs', 2, 6, 'For the LORD gives wisdom; from His mouth come knowledge and understanding.'],
  ['Psalms', 'psalms', 33, 4, 'For the word of the LORD is upright, and all His work is trustworthy.'],
  ['Colossians', 'colossians', 3, 15, 'Let the peace of Christ rule in your hearts, for to this you were called as members of one body. And be thankful.'],
  ['John', 'john', 8, 12, 'Once again, Jesus spoke to the people and said, "I am the light of the world. Whoever follows Me will never walk in darkness but will have the light of life."'],
  ['Psalms', 'psalms', 111, 10, 'The fear of the LORD is the beginning of wisdom. All who follow His precepts gain rich understanding. His praise endures forever.'],
  ['Ephesians', 'ephesians', 2, 10, 'For we are God\'s workmanship, created in Christ Jesus for good works, which God prepared in advance as our way of life.'],
  ['Proverbs', 'proverbs', 25, 11, 'A word spoken at the right time is like golden apples in silver settings.'],
  ['Matthew', 'matthew', 5, 6, 'Blessed are those who hunger and thirst for righteousness, for they will be filled.'],
  ['Psalms', 'psalms', 30, 5, 'For His anger is but for a moment, but His favor lasts a lifetime. Weeping may stay the night, but joy comes in the morning.'],
  ['2 Corinthians', '2-corinthians', 12, 9, 'But He said to me, "My grace is sufficient for you, for My power is perfected in weakness."'],
  ['Psalms', 'psalms', 48, 14, 'For this God is our God forever and ever; He will be our guide even to the end.'],
  ['Proverbs', 'proverbs', 16, 9, 'A man\'s heart plans his course, but the LORD determines his steps.'],
  ['Romans', 'romans', 12, 21, 'Do not be overcome by evil, but overcome evil with good.'],
  ['Psalms', 'psalms', 119, 11, 'I have hidden Your word in my heart that I might not sin against You.'],
  ['Mark', 'mark', 10, 27, 'Jesus looked at them and said, "With man this is impossible, but not with God. For all things are possible with God."'],
  ['Psalms', 'psalms', 95, 1, 'Come, let us sing for joy to the LORD; let us shout to the Rock of our salvation.'],
  ['James', 'james', 1, 2, 'Consider it pure joy, my brothers, when you encounter trials of many kinds,'],
  ['Psalms', 'psalms', 71, 5, 'For You are my hope, O Lord GOD, my confidence from my youth.'],
  ['1 Peter', '1-peter', 2, 9, 'But you are a chosen people, a royal priesthood, a holy nation, a people for God\'s own possession, so that you may proclaim the praises of the One who called you out of darkness into His marvelous light.'],
  ['Psalms', 'psalms', 8, 1, 'O LORD, our Lord, how majestic is Your name in all the earth! You have set Your glory above the heavens.'],
  ['Proverbs', 'proverbs', 24, 16, 'For though a righteous man falls seven times, he will get up, but the wicked will stumble into ruin.'],
  ['John', 'john', 17, 17, 'Sanctify them by the truth; Your word is truth.'],

  // June (30)
  ['Psalms', 'psalms', 36, 5, 'Your loving devotion, O LORD, reaches to the heavens, Your faithfulness to the clouds.'],
  ['Proverbs', 'proverbs', 17, 17, 'A friend loves at all times, and a brother is born for adversity.'],
  ['John', 'john', 1, 14, 'The Word became flesh and made His dwelling among us. We have seen His glory, the glory of the one and only Son from the Father, full of grace and truth.'],
  ['Romans', 'romans', 14, 8, 'If we live, we live to the Lord; and if we die, we die to the Lord. So whether we live or die, we belong to the Lord.'],
  ['Psalms', 'psalms', 25, 4, 'Show me Your ways, O LORD; teach me Your paths.'],
  ['Isaiah', 'isaiah', 40, 8, 'The grass withers and the flowers fall, but the word of our God stands forever.'],
  ['Matthew', 'matthew', 18, 20, 'For where two or three gather together in My name, there am I with them.'],
  ['Psalms', 'psalms', 112, 1, 'Hallelujah! Blessed is the man who fears the LORD, who greatly delights in His commandments.'],
  ['Hebrews', 'hebrews', 12, 2, 'Let us fix our eyes on Jesus, the author and perfecter of our faith, who for the joy set before Him endured the cross, scorning its shame, and sat down at the right hand of the throne of God.'],
  ['Proverbs', 'proverbs', 13, 20, 'Walk with the wise and become wise, but a companion of fools will be destroyed.'],
  ['Psalms', 'psalms', 68, 19, 'Blessed be the Lord, who daily bears our burdens, the God of our salvation.'],
  ['Philippians', 'philippians', 1, 6, 'being confident of this, that He who began a good work in you will carry it on to completion until the day of Christ Jesus.'],
  ['John', 'john', 15, 13, 'Greater love has no one than this, that he lay down his life for his friends.'],
  ['Psalms', 'psalms', 119, 9, 'How can a young man keep his way pure? By guarding it according to Your word.'],
  ['Ephesians', 'ephesians', 6, 11, 'Put on the full armor of God, so that you can make your stand against the devil\'s schemes.'],
  ['Proverbs', 'proverbs', 6, 23, 'For a commandment is a lamp, teaching is a light, and the reproofs of discipline are the way to life,'],
  ['Matthew', 'matthew', 5, 8, 'Blessed are the pure in heart, for they will see God.'],
  ['Psalms', 'psalms', 127, 1, 'Unless the LORD builds the house, its builders labor in vain; unless the LORD watches over the city, the watchmen stand guard in vain.'],
  ['Titus', 'titus', 3, 5, 'He saved us, not by the righteous deeds we had done, but according to His mercy, through the washing of new birth and renewal by the Holy Spirit,'],
  ['Psalms', 'psalms', 19, 14, 'May the words of my mouth and the meditation of my heart be pleasing in Your sight, O LORD, my Rock and my Redeemer.'],
  ['Proverbs', 'proverbs', 21, 2, 'Every way of a man is right in his own eyes, but the LORD weighs the hearts.'],
  ['Romans', 'romans', 8, 31, 'What then shall we say in response to these things? If God is for us, who can be against us?'],
  ['Psalms', 'psalms', 61, 2, 'From the ends of the earth I call out to You, I call out as my heart grows faint; lead me to the rock that is higher than I.'],
  ['Luke', 'luke', 6, 31, 'Do unto others as you would have them do unto you.'],
  ['Psalms', 'psalms', 136, 1, 'Give thanks to the LORD, for He is good. His loving devotion endures forever.'],
  ['1 Corinthians', '1-corinthians', 15, 58, 'Therefore, my beloved brothers, be steadfast, immovable, always excelling in the work of the Lord, knowing that your labor in the Lord is not in vain.'],
  ['Psalms', 'psalms', 37, 5, 'Commit your way to the LORD; trust in Him, and He will act.'],
  ['Proverbs', 'proverbs', 28, 26, 'He who trusts in himself is a fool, but he who walks in wisdom will be safe.'],
  ['John', 'john', 20, 31, 'But these are written so that you may believe that Jesus is the Christ, the Son of God, and that by believing you may have life in His name.'],
  ['Psalms', 'psalms', 92, 1, 'It is good to praise the LORD and make music to Your name, O Most High,'],

  // July (31)
  ['Psalms', 'psalms', 27, 14, 'Wait on the LORD; be strong, and may your heart be stout. Wait on the LORD.'],
  ['Proverbs', 'proverbs', 29, 25, 'The fear of man is a snare, but whoever trusts in the LORD is set securely on high.'],
  ['John', 'john', 14, 1, 'Do not let your hearts be troubled. You believe in God; believe in Me as well.'],
  ['Romans', 'romans', 12, 10, 'Be devoted to one another in brotherly love. Outdo one another in showing honor.'],
  ['Psalms', 'psalms', 34, 18, 'The LORD is near to the brokenhearted and saves the crushed in spirit.'],
  ['Isaiah', 'isaiah', 12, 2, 'Surely God is my salvation; I will trust and not be afraid. For the LORD GOD is my strength and my song, and He also has become my salvation.'],
  ['Matthew', 'matthew', 28, 20, 'And surely I am with you always, even to the end of the age.'],
  ['Psalms', 'psalms', 116, 1, 'I love the LORD because He has heard my voice and my pleas for mercy.'],
  ['Philippians', 'philippians', 3, 14, 'I press on toward the goal to win the prize of God\'s heavenly calling in Christ Jesus.'],
  ['Proverbs', 'proverbs', 15, 33, 'The fear of the LORD is the instruction of wisdom, and humility comes before honor.'],
  ['Psalms', 'psalms', 37, 23, 'The steps of a man are established by the LORD, and He takes delight in his way.'],
  ['Colossians', 'colossians', 3, 17, 'And whatever you do, in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through Him.'],
  ['John', 'john', 3, 30, 'He must increase, but I must decrease.'],
  ['Psalms', 'psalms', 139, 23, 'Search me, O God, and know my heart; test me and know my concerns.'],
  ['Ephesians', 'ephesians', 4, 2, 'with all humility and gentleness, with patience, bearing with one another in love,'],
  ['Proverbs', 'proverbs', 30, 5, 'Every word of God is flawless; He is a shield to those who take refuge in Him.'],
  ['Matthew', 'matthew', 6, 6, 'But when you pray, go into your inner room, shut your door, and pray to your Father, who is unseen. And your Father, who sees what is done in secret, will reward you.'],
  ['Psalms', 'psalms', 13, 5, 'But I have trusted in Your loving devotion; my heart will rejoice in Your salvation.'],
  ['2 Corinthians', '2-corinthians', 4, 18, 'So we fix our eyes not on what is seen, but on what is unseen. For what is seen is temporary, but what is unseen is eternal.'],
  ['Psalms', 'psalms', 104, 33, 'I will sing to the LORD all my life; I will sing praise to my God as long as I live.'],
  ['Proverbs', 'proverbs', 20, 7, 'The righteous man walks in his integrity; blessed are his children after him.'],
  ['Romans', 'romans', 12, 12, 'Be joyful in hope, patient in affliction, persistent in prayer.'],
  ['Psalms', 'psalms', 31, 24, 'Be strong and courageous, all you who put your hope in the LORD.'],
  ['Luke', 'luke', 12, 34, 'For where your treasure is, there your heart will be also.'],
  ['Psalms', 'psalms', 77, 14, 'You are the God who performs wonders; You have revealed Your strength among the peoples.'],
  ['James', 'james', 3, 17, 'But the wisdom from above is first of all pure, then peaceable, gentle, accommodating, full of mercy and good fruit, impartial, and sincere.'],
  ['Psalms', 'psalms', 119, 165, 'Great peace have those who love Your law, and nothing can make them stumble.'],
  ['Hebrews', 'hebrews', 11, 6, 'And without faith it is impossible to please God, because anyone who approaches Him must believe that He exists and that He rewards those who earnestly seek Him.'],
  ['Matthew', 'matthew', 4, 4, 'But Jesus answered, "It is written: Man shall not live on bread alone, but on every word that comes from the mouth of God."'],
  ['Psalms', 'psalms', 9, 1, 'I will give thanks to the LORD with all my heart; I will tell of all Your wonders.'],
  ['Revelation', 'revelation', 3, 20, 'Behold, I stand at the door and knock. If anyone hears My voice and opens the door, I will come in and dine with him, and he with Me.'],

  // August - December (153 more verses to reach 365)
  // These fill out the remaining months with strong selections
  ['Psalms', 'psalms', 46, 5, 'God is within her; she will not be toppled. God will help her when morning dawns.'],
  ['Proverbs', 'proverbs', 3, 9, 'Honor the LORD with your wealth, with the firstfruits of all your produce.'],
  ['John', 'john', 5, 24, 'Truly, truly, I tell you, whoever hears My word and believes Him who sent Me has eternal life and will not come under judgment. Indeed, he has crossed over from death to life.'],
  ['Romans', 'romans', 13, 10, 'Love does no wrong to its neighbor. Therefore love is the fulfillment of the law.'],
  ['Psalms', 'psalms', 22, 19, 'But You, O LORD, be not far off. O my Strength, come quickly to help me.'],
  ['Isaiah', 'isaiah', 40, 29, 'He gives power to the faint and increases the strength of the weak.'],
  ['Matthew', 'matthew', 10, 31, 'So do not be afraid; you are worth more than many sparrows.'],
  ['Psalms', 'psalms', 28, 7, 'The LORD is my strength and my shield; my heart trusts in Him, and I am helped. Therefore my heart leaps for joy, and I give thanks to Him with my song.'],
  ['Philippians', 'philippians', 4, 8, 'Finally, brothers, whatever is true, whatever is honorable, whatever is right, whatever is pure, whatever is lovely, whatever is admirable— if anything is excellent or praiseworthy— think on these things.'],
  ['Proverbs', 'proverbs', 8, 11, 'For wisdom is better than rubies, and nothing desirable can compare to her.'],
  ['Psalms', 'psalms', 52, 8, 'But I am like an olive tree flourishing in the house of God; I trust in God\'s loving devotion forever and ever.'],
  ['1 Corinthians', '1-corinthians', 2, 9, 'But as it is written: "No eye has seen, no ear has heard, no heart has imagined, what God has prepared for those who love Him."'],
  ['Psalms', 'psalms', 130, 5, 'I wait for the LORD; my soul waits, and in His word I put my hope.'],
  ['Proverbs', 'proverbs', 23, 26, 'My son, give me your heart, and let your eyes delight in my ways.'],
  ['Matthew', 'matthew', 5, 14, 'You are the light of the world. A city on a hill cannot be hidden.'],
  ['Psalms', 'psalms', 40, 3, 'He put a new song in my mouth, a hymn of praise to our God. Many will see and fear and put their trust in the LORD.'],
  ['Romans', 'romans', 5, 1, 'Therefore, since we have been justified through faith, we have peace with God through our Lord Jesus Christ,'],
  ['Psalms', 'psalms', 85, 10, 'Loving devotion and faithfulness have joined together; righteousness and peace have kissed.'],
  ['Ephesians', 'ephesians', 1, 7, 'In Him we have redemption through His blood, the forgiveness of our trespasses, according to the riches of His grace'],
  ['Proverbs', 'proverbs', 9, 10, 'The fear of the LORD is the beginning of wisdom, and knowledge of the Holy One is understanding.'],
  ['John', 'john', 14, 26, 'But the Advocate, the Holy Spirit, whom the Father will send in My name, will teach you all things and will remind you of everything I have told you.'],
  ['Psalms', 'psalms', 97, 10, 'You who love the LORD, hate evil! He preserves the souls of His saints and delivers them from the hand of the wicked.'],
  ['Galatians', 'galatians', 2, 20, 'I have been crucified with Christ, and I no longer live, but Christ lives in me. The life I live in the body, I live by faith in the Son of God, who loved me and gave Himself up for me.'],
  ['Psalms', 'psalms', 57, 10, 'For Your loving devotion reaches to the heavens, and Your faithfulness to the clouds.'],
  ['Proverbs', 'proverbs', 11, 2, 'When pride comes, disgrace follows, but with humility comes wisdom.'],
  ['Matthew', 'matthew', 6, 21, 'For where your treasure is, there your heart will be also.'],
  ['Psalms', 'psalms', 65, 4, 'Blessed are those You choose and bring near to dwell in Your courts. We are filled with the goodness of Your house, the holiness of Your temple.'],
  ['2 Peter', '2-peter', 3, 9, 'The Lord is not slow in keeping His promise as some understand slowness, but is patient with you, not wanting anyone to perish but everyone to come to repentance.'],
  ['Psalms', 'psalms', 108, 4, 'For Your loving devotion extends above the heavens, and Your faithfulness reaches to the clouds.'],
  ['Proverbs', 'proverbs', 16, 24, 'Pleasant words are a honeycomb, sweet to the soul and healing to the bones.'],
  ['John', 'john', 6, 68, 'Simon Peter answered, "Lord, to whom would we go? You have the words of eternal life."'],
  ['Romans', 'romans', 8, 18, 'For I consider that our present sufferings are not worth comparing with the glory that will be revealed in us.'],
  ['Psalms', 'psalms', 113, 3, 'From the rising of the sun to its setting, the name of the LORD is to be praised.'],
  ['Isaiah', 'isaiah', 54, 10, '"Though the mountains may be removed and the hills may be shaken, My loving devotion will not depart from you, and My covenant of peace will not be broken," says the LORD, who has compassion on you.'],
  ['Matthew', 'matthew', 5, 9, 'Blessed are the peacemakers, for they will be called sons of God.'],
  ['Psalms', 'psalms', 119, 130, 'The unfolding of Your words gives light; it gives understanding to the simple.'],
  ['Philippians', 'philippians', 4, 19, 'And my God will supply all your needs according to His glorious riches in Christ Jesus.'],
  ['Proverbs', 'proverbs', 17, 22, 'A joyful heart is good medicine, but a broken spirit dries up the bones.'],
  ['Psalms', 'psalms', 37, 7, 'Be still before the LORD and wait patiently for Him; do not fret when men prosper in their ways, when they carry out wicked schemes.'],
  ['1 Corinthians', '1-corinthians', 13, 13, 'And now these three remain: faith, hope, and love; but the greatest of these is love.'],
  ['Psalms', 'psalms', 119, 114, 'You are my hiding place and my shield; I put my hope in Your word.'],
  ['Proverbs', 'proverbs', 21, 3, 'To do righteousness and justice is more desirable to the LORD than sacrifice.'],
  ['Matthew', 'matthew', 11, 30, 'For My yoke is easy and My burden is light.'],
  ['Psalms', 'psalms', 23, 6, 'Surely goodness and mercy will follow me all the days of my life, and I will dwell in the house of the LORD forever.'],
  ['John', 'john', 14, 15, 'If you love Me, you will keep My commandments.'],
  ['Romans', 'romans', 11, 33, 'O the depth of the riches of the wisdom and knowledge of God! How unsearchable are His judgments, and how untraceable His ways!'],
  ['Psalms', 'psalms', 145, 9, 'The LORD is good to all; His compassion rests on all He has made.'],
  ['Ephesians', 'ephesians', 5, 2, 'and walk in love, just as Christ loved us and gave Himself up for us as a fragrant sacrificial offering to God.'],
  ['Proverbs', 'proverbs', 4, 7, 'Wisdom is supreme; therefore acquire wisdom. And whatever you acquire, gain understanding.'],
  ['Psalms', 'psalms', 126, 3, 'The LORD has done great things for us; we are filled with joy.'],
  ['Hebrews', 'hebrews', 10, 23, 'Let us hold resolutely to the hope we profess, for He who promised is faithful.'],
  ['Psalms', 'psalms', 47, 1, 'Clap your hands, all you peoples; shout to God with a jubilant cry.'],
  ['Proverbs', 'proverbs', 14, 26, 'In the fear of the LORD is strong confidence, and His children will have a place of refuge.'],
  ['Matthew', 'matthew', 17, 20, '"Because of your little faith," He answered. "For truly I tell you, if you have faith the size of a mustard seed, you can say to this mountain, \'Move from here to there,\' and it will move. Nothing will be impossible for you."'],
  ['Psalms', 'psalms', 33, 12, 'Blessed is the nation whose God is the LORD, the people He has chosen as His inheritance.'],
  ['1 John', '1-john', 5, 14, 'And this is the confidence that we have before Him: If we ask anything according to His will, He hears us.'],
  ['Psalms', 'psalms', 119, 89, 'Your word, O LORD, is everlasting; it is firmly fixed in the heavens.'],
  ['Proverbs', 'proverbs', 19, 17, 'Kindness to the poor is a loan to the LORD, and He will repay the lender.'],
  ['John', 'john', 12, 46, 'I have come into the world as a light, so that no one who believes in Me should remain in darkness.'],
  ['Romans', 'romans', 8, 26, 'In the same way, the Spirit helps us in our weakness. For we do not know how we ought to pray, but the Spirit Himself intercedes for us with groans too deep for words.'],
  ['Psalms', 'psalms', 86, 15, 'But You, O Lord, are a compassionate and gracious God, slow to anger, abounding in loving devotion and faithfulness.'],
  ['Isaiah', 'isaiah', 41, 13, 'For I am the LORD your God who takes hold of your right hand and tells you, "Do not fear, I will help you."'],
  ['Matthew', 'matthew', 5, 3, 'Blessed are the poor in spirit, for theirs is the kingdom of heaven.'],
  ['Psalms', 'psalms', 34, 1, 'I will bless the LORD at all times; His praise will always be on my lips.'],
  ['1 Peter', '1-peter', 3, 15, 'But in your hearts sanctify Christ as Lord. Always be prepared to give a defense to everyone who asks you the reason for the hope that you have. But respond with gentleness and respect,'],
  ['Psalms', 'psalms', 100, 5, 'For the LORD is good, and His loving devotion endures forever; His faithfulness continues to all generations.'],
  ['Proverbs', 'proverbs', 3, 24, 'When you lie down, you will not be afraid; when you rest, your sleep will be sweet.'],
  ['John', 'john', 16, 13, 'However, when the Spirit of truth comes, He will guide you into all truth. For He will not speak on His own, but He will speak what He hears, and He will declare to you what is to come.'],
  ['Romans', 'romans', 10, 17, 'Consequently, faith comes by hearing, and hearing by the word of Christ.'],
  ['Psalms', 'psalms', 71, 8, 'My mouth is filled with Your praise, declaring Your splendor all day long.'],
  ['Philippians', 'philippians', 2, 14, 'Do everything without complaining or arguing,'],
  ['Psalms', 'psalms', 18, 30, 'As for God, His way is perfect; the word of the LORD is flawless. He is a shield to all who take refuge in Him.'],
  ['Proverbs', 'proverbs', 10, 12, 'Hatred stirs up strife, but love covers all offenses.'],
  ['Matthew', 'matthew', 5, 48, 'Be perfect, therefore, as your heavenly Father is perfect.'],
  ['Psalms', 'psalms', 103, 1, 'Bless the LORD, O my soul, and all that is within me, bless His holy name.'],
  ['Ephesians', 'ephesians', 3, 17, 'so that Christ may dwell in your hearts through faith. Then, being rooted and grounded in love,'],
  ['Psalms', 'psalms', 119, 160, 'The entirety of Your word is truth, and all Your righteous judgments endure forever.'],
  ['Proverbs', 'proverbs', 22, 1, 'A good name is more desirable than great riches; favor is better than silver and gold.'],
  ['John', 'john', 10, 28, 'I give them eternal life, and they will never perish. No one can snatch them out of My hand.'],
  ['Romans', 'romans', 15, 4, 'For everything that was written in the past was written for our instruction, so that through endurance and the encouragement of the Scriptures, we might have hope.'],
  ['Psalms', 'psalms', 46, 7, 'The LORD of Hosts is with us; the God of Jacob is our fortress.'],
  ['Isaiah', 'isaiah', 9, 6, 'For unto us a child is born, unto us a son is given, and the government will be upon His shoulders. And He will be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace.'],
  ['Matthew', 'matthew', 1, 23, '"Behold, the virgin will be with child and will give birth to a son, and they will call Him Immanuel" (which means, "God with us").'],
  ['Psalms', 'psalms', 96, 1, 'Sing a new song to the LORD; sing to the LORD, all the earth.'],
  ['Luke', 'luke', 2, 11, 'Today in the city of David a Savior has been born to you. He is Christ the Lord!'],
  ['Psalms', 'psalms', 98, 1, 'Sing a new song to the LORD, for He has done marvelous things. His right hand and holy arm have gained Him the victory.'],
  ['Proverbs', 'proverbs', 16, 20, 'Whoever heeds instruction will find success, and blessed is he who trusts in the LORD.'],
  ['John', 'john', 1, 12, 'But to all who did receive Him, to those who believed in His name, He gave the right to become children of God—'],
  ['Psalms', 'psalms', 29, 2, 'Ascribe to the LORD the glory due His name; worship the LORD in the splendor of His holiness.'],
  ['Revelation', 'revelation', 22, 21, 'The grace of the Lord Jesus be with all the saints. Amen.'],
  ['Psalms', 'psalms', 91, 11, 'For He will command His angels concerning you to guard you in all your ways.'],
  ['Romans', 'romans', 8, 37, 'No, in all these things we are more than conquerors through Him who loved us.'],
  ['Psalms', 'psalms', 103, 8, 'The LORD is compassionate and gracious, slow to anger, abounding in loving devotion.'],
  ['Proverbs', 'proverbs', 3, 26, 'for the LORD will be your confidence and will keep your foot from the snare.'],
  ['Matthew', 'matthew', 5, 7, 'Blessed are the merciful, for they will be shown mercy.'],
  ['Psalms', 'psalms', 119, 50, 'This is my comfort in my affliction, that Your promise has given me life.'],
  ['1 Thessalonians', '1-thessalonians', 5, 18, 'Give thanks in every circumstance, for this is God\'s will for you in Christ Jesus.'],
  ['Psalms', 'psalms', 145, 3, 'Great is the LORD and greatly to be praised; His greatness is unsearchable.'],
  ['Proverbs', 'proverbs', 12, 25, 'Anxiety in a man\'s heart weighs it down, but a good word cheers it up.'],
  ['Psalms', 'psalms', 119, 1, 'Blessed are those whose way is blameless, who walk in the law of the LORD.'],
  ['John', 'john', 8, 36, 'So if the Son sets you free, you will be free indeed.'],
  ['Psalms', 'psalms', 23, 3, 'He restores my soul; He guides me in the paths of righteousness for the sake of His name.'],
  ['Isaiah', 'isaiah', 30, 21, 'And whether you turn to the right or to the left, your ears will hear this voice behind you: "This is the way. Walk in it."'],
  ['Psalms', 'psalms', 139, 7, 'Where can I go from Your Spirit? Where can I flee from Your presence?'],
  ['Proverbs', 'proverbs', 15, 13, 'A joyful heart makes a cheerful countenance, but sorrow of the heart crushes the spirit.'],
  ['Matthew', 'matthew', 6, 9, '"So then, this is how you should pray: Our Father in heaven, hallowed be Your name."'],
  ['Psalms', 'psalms', 103, 17, 'But from everlasting to everlasting the loving devotion of the LORD extends to those who fear Him, and His righteousness to their children\'s children,'],
  ['Romans', 'romans', 8, 39, 'neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord.'],
  ['Psalms', 'psalms', 148, 13, 'Let them praise the name of the LORD, for His name alone is exalted; His splendor is above the earth and the heavens.'],
  ['Proverbs', 'proverbs', 23, 12, 'Apply your heart to instruction and your ears to words of knowledge.'],
  ['Hebrews', 'hebrews', 12, 1, 'Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off every encumbrance and the sin that so easily entangles, and let us run with endurance the race set out for us.'],
  ['Psalms', 'psalms', 34, 4, 'I sought the LORD, and He answered me; He delivered me from all my fears.'],
  ['Lamentations', 'lamentations', 3, 23, 'They are new every morning; great is Your faithfulness!'],
  ['Psalms', 'psalms', 119, 103, 'How sweet are Your words to my taste, sweeter than honey to my mouth!'],
  ['1 Corinthians', '1-corinthians', 15, 57, 'But thanks be to God, who gives us the victory through our Lord Jesus Christ!'],
  ['Psalms', 'psalms', 62, 5, 'Rest in God alone, O my soul, for my hope comes from Him.'],
  ['Proverbs', 'proverbs', 18, 24, 'A man of many companions may come to ruin, but there is a friend who sticks closer than a brother.'],
  ['Matthew', 'matthew', 7, 12, 'In everything, then, do to others as you would have them do to you. For this is the essence of the Law and the Prophets.'],
  ['Psalms', 'psalms', 23, 5, 'You prepare a table before me in the presence of my enemies. You anoint my head with oil; my cup overflows.'],
  ['John', 'john', 3, 17, 'For God did not send His Son into the world to condemn the world, but to save the world through Him.'],
  ['Psalms', 'psalms', 119, 71, 'It was good for me to be afflicted, so that I might learn Your statutes.'],
  ['2 Corinthians', '2-corinthians', 9, 8, 'And God is able to make all grace abound to you, so that in all things, at all times, having all that you need, you will abound in every good work.'],
  ['Psalms', 'psalms', 73, 28, 'But as for me, it is good to draw near to God. I have made the Lord GOD my refuge, that I may proclaim all Your works.'],
  ['Isaiah', 'isaiah', 40, 11, 'He tends His flock like a shepherd; He gathers the lambs in His arms and carries them close to His heart. He gently leads the nursing ewes.'],
  ['Psalms', 'psalms', 119, 18, 'Open my eyes that I may see wondrous things from Your law.'],
  ['Revelation', 'revelation', 1, 8, '"I am the Alpha and the Omega," says the Lord God, "who is and was and is to come— the Almighty."'],
]

/**
 * Get the verse of the day, deterministic by date
 */
export function getVerseOfTheDay(date?: Date): DailyVerse {
  const d = date || new Date()
  // Day of year (0-364)
  const start = new Date(d.getFullYear(), 0, 0)
  const diff = d.getTime() - start.getTime()
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24)) - 1

  const index = ((dayOfYear % DAILY_VERSES.length) + DAILY_VERSES.length) % DAILY_VERSES.length
  const [book, slug, chapter, verse, text] = DAILY_VERSES[index]

  return {
    book,
    slug,
    chapter,
    verse,
    text,
    reference: `${book} ${chapter}:${verse}`,
  }
}
